---
- hosts: localhost
  connection: local
  become: yes
  
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
     
    - name: Unlink default Nginx conf
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default

    - name: Create Nginx logs subdirectory
      file:
        path: /var/www/reverse-proxy
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create subdirectory for containers
      file:
        path: /var/www/docker
        state: directory
        mode: '0755'
        owner: mike
        group: mandj

    - name: Start / Reload Nginx
      service:
        name: nginx
        state: reloaded
        enabled: yes
