---
- hosts: localhost
  connection: local
  become: yes
  
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        
    - name: Replace existing Nginx default config file
      get_url:
        url: https://raw.githubusercontent.com/Bicko/docker-prep/master/default.nginx
        dest: /etc/nginx/sites-available/default
        mode: '0644'
        owner: root
        group: root
     
    - name: Ensure default Nginx conf is linked
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        owner: root
        group: root
        state: link
        

    - name: Create Nginx logs subdirectory
      file:
        path: /var/www/reverse-proxy
        state: directory
        mode: '0755'
        owner: mike
        group: mandj
        
    - name: Create subdirectory for default Nginx logs
      file:
        path: /var/www/reverse-proxy/default
        state: directory
        mode: '0755'
        owner: mike
        group: mandj

    - name: Create subdirectory for containers
      file:
        path: /var/www/docker
        state: directory
        mode: '0755'
        owner: mike
        group: mandj

    - name: Start / Reload Nginx
      service:
        name: nginx
        state: reloaded
        enabled: yes
