---
- hosts: localhost
  connection: local
  become: yes
  vars:
    domain_name: anaya.strangerthandata.com
  
  tasks:
    - name: Fetch Nginx reverse proxy config file for {{ domain_name }}
      get_url:
        url: https://raw.githubusercontent.com/Bicko/docker-prep/master/{{ domain_name }}.nginx
        dest: /etc/nginx/sites-available/{{ domain_name }}
        mode: '0644'
        owner: root
        group: root

    - name: Create directories for {{ domain_name }}
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: mike
        group: mandj
      loop:
        - /var/www/reverse-proxy/{{ domain_name }}
        - /var/www/docker/{{ domain_name }}
        - /var/www/docker/{{ domain_name }}/logs
        - /var/www/docker/{{ domain_name }}/conf

    - name: Create html directory for {{ domain_name }} with different ownership
      file:
        path: "/var/www/docker/{{ domain_name }}/html"
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Create sites-enabled symlink
      file:
        src: /etc/nginx/sites-available/{{ domain_name }}
        dest: /etc/nginx/sites-enabled/{{ domain_name }}
        owner: root
        group: root
        state: link
        
    - name: Start / Reload Nginx
      service:
        name: nginx
        state: reloaded
        enabled: yes
